# Server
server.port=8081

# H2 Database
#spring.datasource.url=jdbc:h2:mem:authdb
#spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orclpdb1
spring.datasource.username=myapp
spring.datasource.password=mypassword1

# JWT
app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwt.expiration-ms=86400000

# Logging
logging.level.com.example.auth=DEBUG

spring.data.mongodb.uri=mongodb://admin:admin123@localhost:27017/employeedb?authSource=admin
spring.data.mongodb.database=employeedb

# ?? Without authentication ?????????????????????????????????????
# spring.data.mongodb.uri=mongodb://localhost:27017/employeedb

# ?? MongoDB Atlas (cloud) ??????????????????????????????????????
# spring.data.mongodb.uri=mongodb+srv://username:pass@cluster.mongodb.net/employeedb

